"""add_agent_actions_training_logs_evaluation_results

Revision ID: 56bcd0e15759
Revises: a12e718b494a
Create Date: 2026-07-27 21:48:19.014116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bcd0e15759'
down_revision: Union[str, Sequence[str], None] = 'a12e718b494a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('execution_cost', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('market_impact', sa.Float(), nullable=True),
    sa.Column('fill_rate', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('training_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_logs_simulation_id'), ['simulation_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agents_simulation', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orderbook_snapshots', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_obs_simulation', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_in_force', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_orders_simulation', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_seed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('buy_order_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('sell_order_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_foreign_key('fk_trades_simulation', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_trades_sell_order', 'orders', ['sell_order_id'], ['order_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_trades_buy_order', 'orders', ['buy_order_id'], ['order_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trades_simulation', type_='foreignkey')
        batch_op.drop_constraint('fk_trades_sell_order', type_='foreignkey')
        batch_op.drop_constraint('fk_trades_buy_order', type_='foreignkey')
        batch_op.alter_column('sell_order_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('buy_order_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('random_seed')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_simulation', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('time_in_force')
        batch_op.drop_column('remaining_quantity')

    with op.batch_alter_table('orderbook_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_obs_simulation', type_='foreignkey')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agents_simulation', type_='foreignkey')

    with op.batch_alter_table('training_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_logs_simulation_id'))

    op.drop_table('training_logs')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_simulation_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_agent_id'))

    op.drop_table('agent_actions')
    # ### end Alembic commands ###
